spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: nikitatimorin
    password: 18428102
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml